### PR TITLE
app.send: add

### LINKED ISSUE #6: app.send
To send actions from within elements I'm using `.bind()` all over the place:

``` js
  return hx`
    <main>
      <a href="/">single</a>
      <a href="/double">double</a>
      <div>${state.count}</div>
      <button onclick=${app.store.bind(null, { type: 'increment' })}>+1</button>
      <button onclick=${app.store.bind(null, { type: 'decrement' })}>-1</button>
    </main>
  `
```

I think adding a convenience method could make this more to the point:

``` js
  return hx`
    <main>
      <a href="/">single</a>
      <a href="/double">double</a>
      <div>${state.count}</div>
      <button onclick=${app.send({ type: 'increment' })}>+1</button>
      <button onclick=${app.send({ type: 'decrement' })}>-1</button>
    </main>
```

All that's needed for the implementation is to create a thunk:

``` js
app.send = function virtualApp_send (action) {
  return function () {
    app.store(action)
  }
}
```

What do you reckon?

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Implements and closes #6 

Also removed a few trailing spaces from the docs _because OCD_; hope you don't mind.

Thanks!

### CODE REVIEW

**Comment by sethvincent** [comment]
:+1:

**Comment by sethvincent** [comment]
ahhh, I should point out somewhere in the readme that the api docs in the readme are generated by the `npm run build-docs` script, based on the jsdoc comments in index.js.

which means those spaces are generated by `build-docs` and came back! uggg. now i can't unsee those extra spaces.

**Comment by sethvincent** [comment]
published in v2.1.0

**Comment by sethvincent** [comment]
(along with virtual-raf@3)

**Comment by yoshuawuyts** [comment]
:sparkles::sparkles::sparkles:

**Comment by yoshuawuyts** [comment]
fwiw I actually prefer to write docs by hand, as it usually results in cleaner code + cleaner docs; those jsdoc things never really worked for me

**Pull request merged**
